### ISSUE TITLE
Payment refused 010 due to security ?

### ISSUE THREAD

**Issue by ikalangita** [Adyen/adyen-php-sample-code#21]
Getting 
`(
    [errorType] => security
    [errorCode] => 010
    [message] => Not allowed
    [pspReference] => 8614834610386710
    [status] => 403
)`

When trying to pay from : (I set correctly username and password with merchant account)

`$request = array(
	 	"merchantAccount" => "XXXXX",   
	 	"amount.currency" => "EUR",
	 	"amount.value" => "1990",
	 	"reference" => "TEST-PAYMENT-" . date("Y-m-d-H:i:s"),
	 	//"shopperIP" => "ShopperIPAddress",
	 	"shopperEmail" => "shoppermail@gmail.com",
	 	"shopperReference" => "12348",
	 	"fraudOffset" => "0",

	 	"card.billingAddress.street" => "Simon Carmiggeltstraat",
	 	"card.billingAddress.postalCode" => "1011 DJ",
	 	"card.billingAddress.city" => "Amsterdam",
	 	"card.billingAddress.houseNumberOrName" => "6-50",
	 	"card.billingAddress.stateOrProvince" => "",
	 	"card.billingAddress.country" => "NL",

	 	"card.expiryMonth" => "06",
	 	"card.expiryYear" => "2018",
	 	"card.holderName" => "John Smith",
	 	"card.number" => "4111111111111111",
	 	"card.cvc" => "004",
	 	);
	 
	 $ch = curl_init();
	 curl_setopt($ch, CURLOPT_URL, "https://pal-test.adyen.com/pal/servlet/Payment/v18/authorise");
	 curl_setopt($ch, CURLOPT_HEADER, false); 
	 curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC  );
	 curl_setopt($ch, CURLOPT_USERPWD, "ws@myCompany:myPassword");   
	 curl_setopt($ch, CURLOPT_POST,1);
	 curl_setopt($ch, CURLOPT_POSTFIELDS,http_build_query($request));
	 curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

	 $result = curl_exec($ch);
	 
	 if($result === false)
	 	echo "Error: " . curl_error($ch);
	 else{
	 	/**
		 * If the payment passes validation a risk analysis will be done and, depending on the
		 * outcome, an authorisation will be attempted. You receive a
		 * payment response with the following fields:
		 * - pspReference: The reference we assigned to the payment;
		 * - resultCode: The result of the payment. One of Authorised, Refused or Error;
		 * - authCode: An authorisation code if the payment was successful, or blank otherwise;
		 * - refusalReason: If the payment was refused, the refusal reason.
		 */ 

	 	parse_str($result,$result);
	 	echo "==== OUTPUT ";
	 	print_r(($result));
	 }
	 
	 curl_close($ch);`

Thank you

**Comment by guangmian** [comment]
Hi, it could be that your webservice user does not have the rights to perform payments with raw card data yet. Could you reach out to support@adyen.com regarding this?

**Comment by rikterbeek** [comment]
Hi @ikalangita 

I think this is solved by now let us know if not.

Regards,
Rik
Adyen

**Comment by uditkumawat** [comment]
If I am encrypting the customer card data,then how to send that CSE encrypted data to API ?

**Comment by iammomin** [comment]
Hey @rikterbeek ,
I am facing the same issue of error 010.
Will you please help me out of this?
Many Thanks in Advance

**Comment by rikterbeek** [comment]
Hi,

This is an permission reason please contact support@adyen.com so we can check if you provided the right documents to get the role to do CSE payments.

Regards,
Rik
Adyen

**Comment by wesweat** [comment]
Hi, @rikterbeek  

are documents necessary to Create a Payment through the API (HTTP Post) even only in Test mode??

I have created and submitted a password with the ws@comp.... user

**Comment by SMJ93** [comment]
We experienced the same issue when trying to request `paymentMethods`. Fixed it by setting the following permissions:

![Screenshot 2019-12-16 at 10 44 47](https://user-images.githubusercontent.com/2145641/70901901-97a66580-1ff3-11ea-9265-fa2c8696a3cf.png)
