### ISSUE TITLE
Everytime I give it a try, I got this error: 403 [errorCode] => 010 [message] => Not allowed [errorType] => security

### ISSUE THREAD

**Issue by nedimdauti** [Adyen/adyen-php-sample-code#30]
Please help me with this error:

stdClass Object ( [status] => 403 [errorCode] => 010 [message] => Not allowed [errorType] => security [pspReference] => 8515108358548934 )

What am I doing wrong? I use JSON API, why this should be so hard to implement?
Not even a (real) documentation is give for this.

**Comment by rikterbeek** [comment]
Hi @nedimdauti,

You can't provide full card data to us if you are not PCI compliant. Please look at our Client Side Encryption solution if need help please reach out to support@adyen.com.
https://docs.adyen.com/developers/features/client-side-encryption

Regards,
Rik
Adyen

**Comment by Raj-PMP** [comment]
Hi there,

**Trying to do " Submit a Subject Erasure Request with the reference of** https://docs.adyen.com/development-resources/data-protection-api

curl https://ca-test.adyen.com/ca/services/DataProtectionService/v1/requestSubjectErasure \
--
  | -H "x-API-key: YOUR_X-API-KEY" \
  | -H "content-type: application/json" \
  | -d '{
  | "merchantAccount":"YOUR_MERCHANT_ACCOUNT",
  | "pspReference":"9915520502347613",
  | "forceErasure": true
  | }'

**But getting the following error:**

     "status": 403,
    "errorCode": "010",
    "message": "Not allowed",
    "errorType": "security"

Expecting your help
